GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJhc2RmZ2g0NUBnbWFpbC5jb20iLCJpYXQiOjE2ODE2NDMwMzMsImV4cCI6MTY4MTY0MzE1M30.SGRHdAMk1ZzeaCj9efuL8PMSPI_tB2dIwfdcZeZuUlE

### 
POST  http://localhost:3000/register
Content-Type: application/json

{
  "name": "user",
  "email": "asdfgh@gmail.com",
  "password": "Password123",
  "confirmPassword": "Password123",
  "address": "bandung",
  "birthDate": "2022-02-22"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "asdfgh@gmail.com",
    "password": "Password123"
}